project_name: api_gen

env:
  - GO111MODULE=on

builds:
  - main: .
    binary: api_gen
    ldflags:
      - -s -w
      - -X github.com/gcp-kit/fti/common.AppVersion={{.Version}}
    env:
      - CGO_ENABLED=1
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64

archives:
  - name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    replacements:
      darwin: darwin
      linux: linux
      windows: windows
      386: i386
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip

release:
  prerelease: auto
