name: build
on: [pull_request]
jobs:
  golangci-lint:
    name: runner / build_and_run
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: Install JRE
        run: |
          sudo apt update && sudo apt install openjdk-17-jre
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: "npm"
          cache-dependency-path: package-lock.json
      - name: Install emulator
        run: |
          npm ci
      - name: Run emulator
        run: |
          make emulator &
      - name: Ensure samples are generated
        env:
          TZ: Asia/Tokyo
        run: |
          make gen_samples

          clean=$(git status | grep "nothing to commit" || true)
          if [ -z "$clean" ]; then
            git diff
            echo 'Please run "make gen_samples"'
            exit 1
          fi
